export enum CODE {
  UNAUTHORIZED = "UNAUTHORIZED",
  BAD_REQUEST = "BAD_REQUEST",
  UNEXPECTED_ERROR = "UNEXPECTED_ERROR",
  NOT_FOUND = "NOT_FOUND",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  VALIDATION_REQUEST_ERROR = "VALIDATION_REQUEST_ERROR",
  EMAIL_IN_USER = "EMAIL_IN_USER",
}
