export enum CODE {
  UNAUTHORIZED = "UNAUTHORIZED",
  BAD_REQUEST = "BAD_REQUEST",
  UNEXPECTED_ERROR = "UNEXPECTED_ERROR",
  NOT_FOUND = "NOT_FOUND",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  VALIDATION_REQUEST_ERROR = "VALIDATION_REQUEST_ERROR",
  EMAIL_IN_USE = "EMAIL_IN_USE",
  ACCESS_TOKEN_EXPIRED = "ACCESS_TOKEN_EXPIRED",
  REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED",
  REUSE_DETECTION = "REUSE_DETECTION",
}
